### ISSUE TITLE
Enable Sentry suspect commits

### ISSUE THREAD

**Issue by andreogle** [api3dao/api3-dao-dashboard#169]
See: https://docs.sentry.io/product/releases/setup/

**Comment by Siegrift** [comment]
@andreogle I've looked into this and it seems very hard to do since we use Fleek which deploys automatically (as githook) and to enable this we need to link the commits of the released version to Sentry (https://docs.sentry.io/product/releases/suspect-commits/)

I also think it's not really needed as this will (hopefully) be set and forget thingy and we will not commit much after it's launched.

**Comment by andreogle** [comment]
Sounds good. Thanks for looking into this
