### ISSUE TITLE
Function signature doesn't get verified

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#263]
The dashboard doesn't verify function signatures and allows proposals with invalid function signatures to be created (https://api3.eth.link/#/history/secondary-13)

There is no utility function for verifying signatures in ethers v5, but there is a workaround, see https://github.com/ethers-io/ethers.js/issues/1101 (Edit: we already implement the workaround)

**Comment by Siegrift** [comment]
Some validation is done by https://github.com/api3dao/api3-dao-dashboard/blob/main/src/logic/proposals/encoding/encoding.ts#L80 and it does catch some bugs (e.g. `unit` instead of `uint` https://github.com/api3dao/api3-dao-dashboard/blob/main/cypress/integration/new-proposal.spec.ts#L29)

unfortunately it doesn't validate spaces properly...

**Comment by bbenligiray** [comment]
How does that work? When I run `ethers.utils.FunctionFragment.from("transfer(address, unit256)")` on https://playground.ethers.org/ it doesn't throw.

**Comment by bbenligiray** [comment]
You're right, and that's essentially the workaround they propose in the ethers.js issue. I'm still keeping this issue open in case a function signature verification function gets implemented in ethers v6 that can catch things like `(address,uint256)transfer` (though I doubt it)

**Comment by bbenligiray** [comment]
We now do a decent bit of validation
