### ISSUE TITLE
Wallet connection fail using Metamask on iOS

### ISSUE THREAD

**Issue by SilverRam13** [api3dao/api3-dao-dashboard#417]
Good day, I noticed on the API3 discord Channel that there have been updates made to the DOA. I tried to connect my Metamask (from an iPhone) but nothing happens. I don’t get re directed to a different page and nothing loads. The “connect wallet” button does show on the UI that I am “clicking it down” but my wallet doesn’t connect. I checked to see if I needed to update my MM wallet but there’s no newer update available. Hopefully this helps, thank you.

**Comment by bbenligiray** [comment]
I tried to replicate this. I have Metamask installed on my phone. I use Safari to go to api3.eth.limo. I select "Connect Wallet". I select Metamask. It takes me to the app store page (which feels wrong). There is an "Open" button instead of an "Install" button because I already have the app installed. I select "Open". It opens the Metamask app but the app just shows me my wallet, doesn't prompt me for a connection. I go back to Safari and it seems like it's trying to connect to Metamask. I see two buttons, "Retry" and "Backup". Selecting either of these successfully takes me to the Metamask app and displays the connection prompt. Once I select "Connect", I'm automatically taken back to the DAO dashboard with my wallet connected. So in my case, it's bumpy but it works.
Somewhat related, if I use the browser in the Metamask app to go to api3.eth.limo everything works fine.

**Comment by SilverRam13** [comment]
Thank you for the reply. I will try those steps. After  I couldn’t connect thru the app on my phone I did use my laptop and went to the website you mentioned (which is the same as within the browser of my metamask app) and I assumed that once I clicked “connect wallet” that I would be able to connect my phone thru a QR code but the DOA dashboard page’s issues on my laptop mirrored the issues from my MM browser extension. 

I appreciate the help and will try your method (if I can figure it out, haha) thanks again.

**Comment by mcoetzee** [comment]
Can you please share what browser you are using (along with the version number of the browser). 

If nothing happens when you click the "Connect Wallet" button, then I suspect you might be using an old browser and updating it to the latest version could solve your problem.

**Comment by SilverRam13** [comment]
@mcoetzee thanks for your response. I am using the Brave Browser (2nd newest version) my phone can’t download the newest version so I will try using a different browser as my default browser and see if I can connect my wallet and let you know if it worked properly. Thank you.

**Comment by SilverRam13** [comment]
@mcoetzee i tried using brave, DuckDuckGo and safari as my default browsers and still no luck connecting my wallet. I’m able to connect my metamask to different ETH Dapps no problem. I find it odd there’s not more people with this issue.

**Comment by mcoetzee** [comment]
> Can you please share what browser you are using (along with the version number of the browser).

I was asking if you could share the browser you use on your laptop. E.g. I am using Chrome v114 (on macOS):
<img width="467" alt="Screenshot 2023-06-26 at 10 32 28" src="https://github.com/api3dao/api3-dao-dashboard/assets/747979/090d8b94-2999-402c-841f-9dd1f412c645">

Also, are you able to connect to this test dapp: https://lab.web3modal.com/with-wagmi/react

**Comment by bbenligiray** [comment]
Closing for being inactive for too long
