### ISSUE TITLE
Rebrand DAO Dashboard - Modals

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#457]
Update styles of modals on the staking page based on the [new designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107801&node-type=section&m=dev). This includes
- Stake / Unstake / Deposit / Withdraw modals
- Unsupported chain modal

**Comment by PrenaamD** [comment]
@Anboias 
Feedback 1
According to the design, "Once staked, you will not be able to unstake your tokens for 7 days." is displayed after the deposit amount is approved, not before. In the implementation, it is always displayed in the deposit modal. 
![Screen Shot 2024-11-26 at 14 34 04 PM](https://github.com/user-attachments/assets/f5af21f5-d29c-4b6e-9d1e-a596b000fde9)

Feedback 2
1. On all the modals, the text should be "How many API3 tokens would you like to ..." instead of "How many tokens would you like to ..."
2. On the Unstaking modal, instead of "Your balance" it should be "Staked tokens"
3. On the Staking modal, instead of "Your balance" it should be "Wallet balance"
4. On the withdraw modal, instead of "Your balance" it should be "Withdrawable tokens"
5. Actually, there seems to be an inconsistency in the design, in the screenshot below, the deposit modal has "your balance" and "wallet balance"

![Screen Shot 2024-11-26 at 14 52 25 PM](https://github.com/user-attachments/assets/584048ec-f838-41fa-84d2-e9794c4015c4)


![Screen Shot 2024-11-26 at 14 45 20 PM](https://github.com/user-attachments/assets/01b6e84a-2afc-4b2f-9761-23b24ed1c50d)

**Comment by Anboias** [comment]
Thanks for the thorough review, @PrenaamD.

I must agree with @peterjurco's comment [here](https://github.com/api3dao/api3-dao-dashboard/issues/460#issuecomment-2501814841). We only focused on the design part of things, leaving the logic as-is. Would you be so kind to check the above with the Design Team as well? We have a Design meeting later today, perhaps you could join us

**Comment by PrenaamD** [comment]
@Anboias I think it can be addressed in a separate issue after checking with the design team.

**Comment by Anboias** [comment]
> I think it can be addressed in a separate issue after checking with the design team.

@PrenaamD, agree 🙏 

Just for the record, I mentioned this issue in yesterday's design call. I was told that, with a few exceptions, Figma typing is outdated and Production version is the source of truth.

**Comment by T9991** [comment]
> Feedback 1
According to the design, "Once staked, you will not be able to unstake your tokens for 7 days." is displayed after the deposit amount is approved, not before. In the implementation, it is always displayed in the deposit modal.

Will update the designs to reflect this.✅  I think we added it after to draw more attention of something appearing.

> Feedback 2: 1. On all the modals, the text should be "How many API3 tokens would you like to ..." instead of "How many tokens would you like to ..."

I completely disagree with this. The token name should be stated.

> 2. On the Unstaking modal, instead of "Your balance" it should be "Staked tokens"

Can't find this in the designs- I assume it was updated during/after a call?

> 3. On the Staking modal, instead of "Your balance" it should be "Wallet balance"

Commented to update ✅

> 4. On the withdraw modal, instead of "Your balance" it should be "Withdrawable tokens" & 5. Actually, there seems to be an inconsistency in the design, in the screenshot below, the deposit modal has "your balance" and "wallet balance"

Commented on the designs to update ✅ Wallet balance should be used for deposit modals. Your balance for staking modals.

**Comment by Anboias** [comment]
@T9991, have you added all your feedback to [this ticket](https://github.com/api3dao/tasks/issues/1535)?

After everything is done on your side, we can pick the ticket up and apply the changes in the code. But it helps to have the full list somewhere so that we know what to change.

**Comment by T9991** [comment]
@Anboias Yes, that's everything
